/* Royal Plast catalog data.
   Generated / replaced by the control panel (admin.html → Publish).
   You can still edit it by hand if you like. */
window.CATALOG_DATA = {
 "settings": {
  "brandName": "Royal Plast",
  "tagline": "Packaging That Sells",
  "logo": "images/logo.jpg",
  "logoMark": "images/logo-mark.png",
  "whatsapp": "201013105930",
  "phones": [
   "010 13 10 59 30",
   "010 14 96 70 28"
  ],
  "phoneAction": "call",
  "website": "www.royalplast-eg.com",
  "qrLink": "https://q.me-qr.com/wbdxvc67",
  "qrCaption": "Scan to follow us",
  "colors": {
   "primary": "#F2222B",
   "secondary": "#1FE0FD",
   "sky": "#5CE6FF",
   "ink": "#0E1A2B",
   "bg": "#F2FCFF"
  },
  "families": [
   {
    "id": "white",
    "name": "White",
    "hex": "#FFFFFF"
   },
   {
    "id": "black",
    "name": "Black",
    "hex": "#151515"
   },
   {
    "id": "clear",
    "name": "Clear",
    "hex": "#DDF3FF"
   },
   {
    "id": "metallic",
    "name": "Gold & Silver",
    "hex": "#D4AF37"
   },
   {
    "id": "colored",
    "name": "Colored",
    "hex": "multi"
   }
  ],
  "cover": {
   "year": "2026",
   "title": "Product",
   "highlight": "Catalog",
   "subtitle": "Premium plastic bottles, jars, pumps, sprayers and caps for beauty, home care and food brands.",
   "note": "Tap any product to view it, then order it on WhatsApp in one tap."
  },
  "back": {
   "thanks": "شكراً لثقتكم",
   "thanksSub": "في كيان رويال بلاست",
   "message": "نفخر بأن نكون جزءاً من نجاحكم",
   "confetti": true
  },
  "labels": {
   "catalogSuffix": " Catalog",
   "contentsTitle": "Contents",
   "contentsSub": "Tap a collection or a color group to jump straight to its page.",
   "howTitle": "How to order",
   "productsWord": "products",
   "orderNow": "Order Now",
   "orderNote": "Opens WhatsApp with all the product details",
   "chooseColor": "Choose a color",
   "view": "View",
   "hintDesktop": "Click the right side to go forward · the left side to go back",
   "hintMobile": "Tap the right side or swipe to turn the page",
   "backWhatsapp": "Chat with our sales team",
   "findPlaceholder": "Find code…"
  },
  "steps": [
   {
    "title": "Browse the catalog",
    "text": "Tap the right side of the book to go forward and the left side to go back."
   },
   {
    "title": "Tap a product",
    "text": "See it large with all its details, and choose the color you need."
   },
   {
    "title": "Order Now",
    "text": "WhatsApp opens with every detail ready to send to our sales team."
   }
  ],
  "layout": {
   "perPage": 6,
   "flipSound": true,
   "flipSpeed": 700,
   "sideArrows": true,
   "showHow": true
  },
  "clickAction": "preview",
  "messageTemplate": "Hello Royal Plast 👋\nI'd like to order / inquire about this item:\n\n📦 Product: {name}\n🔖 Code: {code}\n📂 Collection: {collection}\n🎨 Color group: {family}\n📏 Size: {capacity}\n🧪 Material: {material}\n🔩 Neck size: {neck}\n⚖️ Weight: {weight}\n🎨 Color: {color}\n📦 Packing: {packing}\n\n🖼 Product photo: {image}",
  "codePrefix": "NK",
  "pages": {}
 },
 "collections": [
  {
   "id": "bottles",
   "name": "PET Bottles",
   "code": "24",
   "perPage": "6",
   "groupByFamily": true,
   "description": "Cylinder, bullet, boston-round and shaped PET bottles — clean gloss finish, ready for your label."
  },
  {
   "id": "jars",
   "name": "Jars",
   "code": "63",
   "perPage": "9",
   "groupByFamily": true,
   "description": "Cream jars and canisters in white, black, clear and colors — thick walls and tight-sealing lids."
  },
  {
   "id": "pumps",
   "name": "Lotion & Treatment Pumps",
   "code": "24",
   "perPage": "9",
   "groupByFamily": true,
   "description": "Lotion and treatment pumps in white, black, gold and crystal finishes for creams, serums and soaps."
  },
  {
   "id": "sprayers",
   "name": "Sprayers",
   "code": "20",
   "perPage": "9",
   "groupByFamily": true,
   "description": "Fine-mist sprayers, nasal & throat sprayers and mini triggers for every kind of liquid."
  },
  {
   "id": "caps",
   "name": "Caps & Closures",
   "code": "24",
   "perPage": "9",
   "groupByFamily": true,
   "description": "Disc-top and flip-top caps in white, black, clear and metallic finishes."
  }
 ],
 "products": [
  {
   "id": "p34",
   "code": "",
   "name": "Mini Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-034.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p35",
   "code": "",
   "name": "Boston Round Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-035.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p36",
   "code": "",
   "name": "Square Shoulder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-036.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p37",
   "code": "",
   "name": "Flat Oval Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-037.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p38",
   "code": "",
   "name": "Tall Cylinder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-038.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p39",
   "code": "",
   "name": "Slim Cylinder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-039.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p40",
   "code": "",
   "name": "Bottle · Gold Cap",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-040.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p41",
   "code": "",
   "name": "Throat Spray Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-041.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p42",
   "code": "",
   "name": "Bullet Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-042.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p43",
   "code": "",
   "name": "Wide Neck Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-043.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p44",
   "code": "",
   "name": "Cylinder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-044.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p45",
   "code": "",
   "name": "Long Neck Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-045.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p46",
   "code": "",
   "name": "Straight Cylinder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-046.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p47",
   "code": "",
   "name": "Shoulder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-047.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p48",
   "code": "",
   "name": "Curved Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-048.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p49",
   "code": "",
   "name": "Matte Bullet Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-049.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p50",
   "code": "",
   "name": "Tube Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-050.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p51",
   "code": "",
   "name": "Two-Tone Cylinder",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-051.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p52",
   "code": "",
   "name": "Classic Cylinder",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-052.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p53",
   "code": "",
   "name": "Round Shoulder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-053.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p54",
   "code": "",
   "name": "Boston Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-054.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p55",
   "code": "",
   "name": "Slim Tall Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-055.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p56",
   "code": "",
   "name": "Tall Bullet Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-056.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p57",
   "code": "",
   "name": "Soft Shoulder Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-057.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p58",
   "code": "",
   "name": "Curved Long Neck Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-058.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p59",
   "code": "",
   "name": "Short Wide Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-059.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p60",
   "code": "",
   "name": "Nasal Spray Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-060.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p61",
   "code": "",
   "name": "Petite Bullet Bottle",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-061.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p62",
   "code": "",
   "name": "Compact Cylinder",
   "collection": "bottles",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/bottles-white-062.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p1",
   "code": "",
   "name": "Duo Cream Jar",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-001.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p2",
   "code": "",
   "name": "White Jar · Gold Lid",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-002.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p3",
   "code": "",
   "name": "Black Jar · Gold Ring",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-003.jpg",
   "featured": true,
   "hidden": false
  },
  {
   "id": "p4",
   "code": "",
   "name": "Mini Black Jar",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-004.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p5",
   "code": "",
   "name": "Jar Trio",
   "collection": "jars",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [
    {
     "name": "White",
     "hex": "#FFFFFF"
    },
    {
     "name": "Blue",
     "hex": "#1E88D9"
    },
    {
     "name": "Black",
     "hex": "#151515"
    }
   ],
   "image": "images/products/jars-colored-005.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p6",
   "code": "",
   "name": "Blue Gloss Jar",
   "collection": "jars",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-colored-006.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p7",
   "code": "",
   "name": "Wide Cream Jar",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-007.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p8",
   "code": "",
   "name": "Dome Lid Jar",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-008.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p9",
   "code": "",
   "name": "White Jar · Alu Lid",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-009.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p10",
   "code": "",
   "name": "Mini White Jar",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-010.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p11",
   "code": "",
   "name": "Clear Jar · White Lid",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-011.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p12",
   "code": "",
   "name": "Gold Ring Jar Pair",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-012.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p13",
   "code": "",
   "name": "Tall White Jar",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-013.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p14",
   "code": "",
   "name": "White Jar · Black Lid",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-014.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p15",
   "code": "",
   "name": "Low Black Jar",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-015.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p16",
   "code": "",
   "name": "Clear Round Jar",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-016.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p17",
   "code": "",
   "name": "Shallow Clear Jar",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-017.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p18",
   "code": "",
   "name": "White Canister",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-018.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p19",
   "code": "",
   "name": "Classic Black Jar",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-019.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p20",
   "code": "",
   "name": "Small White Jar Pair",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-020.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p21",
   "code": "",
   "name": "Mini Clear Jars",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [
    {
     "name": "White lid",
     "hex": "#FFFFFF"
    },
    {
     "name": "Black lid",
     "hex": "#151515"
    }
   ],
   "image": "images/products/jars-clear-021.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p22",
   "code": "",
   "name": "Shallow Jar · Gold Lid",
   "collection": "jars",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-white-022.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p23",
   "code": "",
   "name": "Clear Jar · Black Lid",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-023.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p24",
   "code": "",
   "name": "Tall Black Jar",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-024.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p25",
   "code": "",
   "name": "Wide Black Jar",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-025.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p26",
   "code": "",
   "name": "Black & White Canisters",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [
    {
     "name": "Black",
     "hex": "#151515"
    },
    {
     "name": "White",
     "hex": "#FFFFFF"
    }
   ],
   "image": "images/products/jars-black-026.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p27",
   "code": "",
   "name": "Black Jar · Ribbed Lid",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-027.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p28",
   "code": "",
   "name": "Clear Jar · Ribbed Lid",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-028.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p29",
   "code": "",
   "name": "Red Wide Jar",
   "collection": "jars",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-colored-029.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p30",
   "code": "",
   "name": "Gloss Black Jar",
   "collection": "jars",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-black-030.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p31",
   "code": "",
   "name": "Clear Jar · Gold Lid",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-031.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p32",
   "code": "",
   "name": "Open Clear Jar",
   "collection": "jars",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/jars-clear-032.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p33",
   "code": "",
   "name": "Color Cream Jars",
   "collection": "jars",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [
    {
     "name": "Pink",
     "hex": "#E0216F"
    },
    {
     "name": "Blue",
     "hex": "#1E40C8"
    },
    {
     "name": "Mint",
     "hex": "#38D4C0"
    },
    {
     "name": "White",
     "hex": "#FFFFFF"
    },
    {
     "name": "Pearl",
     "hex": "#F4F1E8"
    }
   ],
   "image": "images/products/jars-colored-033.jpg",
   "featured": true,
   "hidden": false
  },
  {
   "id": "p63",
   "code": "",
   "name": "Matte Lotion Pump",
   "collection": "pumps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-black-063.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p71",
   "code": "",
   "name": "Treatment Pump · Gold Ring",
   "collection": "pumps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-white-071.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p72",
   "code": "",
   "name": "Gold Treatment Pump · Black",
   "collection": "pumps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-metallic-072.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p75",
   "code": "",
   "name": "Gold Treatment Pump · White",
   "collection": "pumps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-metallic-075.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p76",
   "code": "",
   "name": "Gold Treatment Pump",
   "collection": "pumps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-metallic-076.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p77",
   "code": "",
   "name": "Black Treatment Pump",
   "collection": "pumps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-black-077.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p78",
   "code": "",
   "name": "Dome Treatment Pump",
   "collection": "pumps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-black-078.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p79",
   "code": "",
   "name": "Gold Lotion Pump",
   "collection": "pumps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-metallic-079.jpg",
   "featured": true,
   "hidden": false
  },
  {
   "id": "p80",
   "code": "",
   "name": "White Treatment Pump",
   "collection": "pumps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-white-080.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p81",
   "code": "",
   "name": "Crystal Lotion Pump · Black",
   "collection": "pumps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-black-081.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p82",
   "code": "",
   "name": "Crystal Lotion Pump · Purple",
   "collection": "pumps",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-colored-082.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p83",
   "code": "",
   "name": "Crystal Lotion Pump · White",
   "collection": "pumps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-white-083.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p84",
   "code": "",
   "name": "Crystal Lotion Pump · Red",
   "collection": "pumps",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-colored-084.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p85",
   "code": "",
   "name": "Screw Lotion Pump",
   "collection": "pumps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-black-085.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p88",
   "code": "",
   "name": "Gold Collar Lotion Pump",
   "collection": "pumps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-metallic-088.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p89",
   "code": "",
   "name": "Classic Lotion Pump",
   "collection": "pumps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-black-089.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p90",
   "code": "",
   "name": "White Lotion Pump",
   "collection": "pumps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-white-090.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p91",
   "code": "",
   "name": "Silver Collar Lotion Pump",
   "collection": "pumps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/pumps-metallic-091.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p64",
   "code": "",
   "name": "Mist Sprayer · Over-cap",
   "collection": "sprayers",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-white-064.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p65",
   "code": "",
   "name": "Nasal Sprayer",
   "collection": "sprayers",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-white-065.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p66",
   "code": "",
   "name": "Fine Mist Sprayer Pair",
   "collection": "sprayers",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-white-066.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p67",
   "code": "",
   "name": "Black Mist Sprayer",
   "collection": "sprayers",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-black-067.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p68",
   "code": "",
   "name": "Black Mini Trigger",
   "collection": "sprayers",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-black-068.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p69",
   "code": "",
   "name": "White Mini Trigger",
   "collection": "sprayers",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-white-069.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p70",
   "code": "",
   "name": "Throat Sprayer",
   "collection": "sprayers",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-black-070.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p73",
   "code": "",
   "name": "Orange Mini Trigger",
   "collection": "sprayers",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-colored-073.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p74",
   "code": "",
   "name": "White Mist Sprayer",
   "collection": "sprayers",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-white-074.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p86",
   "code": "",
   "name": "Gold Mini Trigger",
   "collection": "sprayers",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-metallic-086.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p87",
   "code": "",
   "name": "Yellow Mini Trigger",
   "collection": "sprayers",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-colored-087.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p92",
   "code": "",
   "name": "Black Fine Mist",
   "collection": "sprayers",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-black-092.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p93",
   "code": "",
   "name": "Purple Mini Trigger",
   "collection": "sprayers",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/sprayers-colored-093.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p94",
   "code": "",
   "name": "Black Disc Top Cap",
   "collection": "caps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-black-094.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p95",
   "code": "",
   "name": "Flip Cap · Gold Band",
   "collection": "caps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-white-095.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p96",
   "code": "",
   "name": "Silver Disc Top Cap",
   "collection": "caps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-metallic-096.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p97",
   "code": "",
   "name": "Gold Disc Top Cap",
   "collection": "caps",
   "family": "metallic",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-metallic-097.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p98",
   "code": "",
   "name": "Clear Flip Cap",
   "collection": "caps",
   "family": "clear",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-clear-098.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p99",
   "code": "",
   "name": "Black Flip Cap",
   "collection": "caps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-black-099.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p100",
   "code": "",
   "name": "White Disc Top Cap",
   "collection": "caps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-white-100.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p101",
   "code": "",
   "name": "Matte Black Disc Cap",
   "collection": "caps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-black-101.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p102",
   "code": "",
   "name": "Black Flip Cap · Gold Band",
   "collection": "caps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-black-102.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p103",
   "code": "",
   "name": "Large Flip Cap · Gold Band",
   "collection": "caps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-white-103.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p104",
   "code": "",
   "name": "Black Flip Cap · Gold Ring",
   "collection": "caps",
   "family": "black",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-black-104.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p105",
   "code": "",
   "name": "White Flip Cap",
   "collection": "caps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-white-105.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p106",
   "code": "",
   "name": "Turquoise Flip Cap",
   "collection": "caps",
   "family": "colored",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-colored-106.jpg",
   "featured": false,
   "hidden": false
  },
  {
   "id": "p107",
   "code": "",
   "name": "Round Flip Cap",
   "collection": "caps",
   "family": "white",
   "capacity": "",
   "material": "",
   "neck": "",
   "weight": "",
   "packing": "",
   "description": "",
   "colors": [],
   "image": "images/products/caps-white-107.jpg",
   "featured": false,
   "hidden": false
  }
 ]
};
